// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InteractiveScheduleUad.Api.Migrations
{
    [DbContext(typeof(InteractiveScheduleUadApiDbContext))]
    [Migration("20230710160901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassType")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId1")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId2")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId3")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId4")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId5")
                        .HasColumnType("integer");

                    b.Property<int?>("WeekScheduleId6")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WeekScheduleId");

                    b.HasIndex("WeekScheduleId1");

                    b.HasIndex("WeekScheduleId2");

                    b.HasIndex("WeekScheduleId3");

                    b.HasIndex("WeekScheduleId4");

                    b.HasIndex("WeekScheduleId5");

                    b.HasIndex("WeekScheduleId6");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Jti")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.StudentsGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FirstWeekScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SecondWeekScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstWeekScheduleId");

                    b.HasIndex("SecondWeekScheduleId");

                    b.ToTable("StudentsGroups");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.WeekSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("WeekSchedule");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Lesson", b =>
                {
                    b.HasOne("InteractiveScheduleUad.Api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("InteractiveScheduleUad.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("InteractiveScheduleUad.Api.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Friday")
                        .HasForeignKey("WeekScheduleId");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Monday")
                        .HasForeignKey("WeekScheduleId1");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Saturday")
                        .HasForeignKey("WeekScheduleId2");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Sunday")
                        .HasForeignKey("WeekScheduleId3");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Thursday")
                        .HasForeignKey("WeekScheduleId4");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Tuesday")
                        .HasForeignKey("WeekScheduleId5");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", null)
                        .WithMany("Wednesday")
                        .HasForeignKey("WeekScheduleId6");

                    b.Navigation("Room");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.StudentsGroup", b =>
                {
                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", "FirstWeekSchedule")
                        .WithMany()
                        .HasForeignKey("FirstWeekScheduleId");

                    b.HasOne("InteractiveScheduleUad.Api.Models.WeekSchedule", "SecondWeekSchedule")
                        .WithMany()
                        .HasForeignKey("SecondWeekScheduleId");

                    b.Navigation("FirstWeekSchedule");

                    b.Navigation("SecondWeekSchedule");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.Teacher", b =>
                {
                    b.HasOne("InteractiveScheduleUad.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InteractiveScheduleUad.Api.Models.WeekSchedule", b =>
                {
                    b.Navigation("Friday");

                    b.Navigation("Monday");

                    b.Navigation("Saturday");

                    b.Navigation("Sunday");

                    b.Navigation("Thursday");

                    b.Navigation("Tuesday");

                    b.Navigation("Wednesday");
                });
#pragma warning restore 612, 618
        }
    }
}
