version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/${CERT_FILE_NAME}
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/certs/${KEY_FILE_NAME}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${CERT_FOLDER_PATH}:/app/certs:ro